### ISSUE TITLE
Google Analytics 4

### ISSUE THREAD

**Issue by selwynorren** [thirtybees/gapi#1]
Hi Guys,

Is this compatible with the new GA-4 code?

**Comment by getdatakick** [comment]
I believe so. Well, gapi itself should be agnostic to the data collection method. It shouldn't matter if the data were collected using legacy analytics.js or by new ga4

**Comment by selwynorren** [comment]
@getdatakick so I have tested it a fair amount. The Google analytics works perfectly and I have 100% data flow in analytics itself, however this module is definitely not working as expected.

There is a permanent error in red with the following message:
Cannot retrieve test results or there is no data in your account, yet

However there is definitely data in the account. I am running a brand new install of the 1.5 version of Thirtybees.
